# Generated by Django 5.0.6 on 2024-07-03 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yellow', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='yellow_F',
            new_name='yellow_M',
        ),
    ]
