# Generated by Django 5.0 on 2024-07-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellow', '0002_rename_yellow_f_yellow_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='yellow_m',
            name='Course',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yellow_m',
            name='Name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yellow_m',
            name='Phone',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
