# Generated by Django 5.0 on 2024-07-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellow', '0003_yellow_m_course_yellow_m_name_yellow_m_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yellow_m',
            name='Course',
            field=models.CharField(choices=[('Office Management', 'Office Management'), ('Grapics Design', 'Grapics Design'), ('Web Development', 'Web Development'), ('Python Programming', 'Python Programmin'), ('Digital Marketing', 'Digital Marketing')], max_length=200),
        ),
    ]
