# Generated by Django 5.0 on 2024-07-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellow', '0004_alter_yellow_m_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yellow_m',
            name='Course',
            field=models.CharField(max_length=200),
        ),
    ]
